# Matrix Factorization cải tiến 
Thêm tốc độ học learning_rate

In [18]:
import numpy as np
# np.random.seed(4)
def MF_update(A, K, eta=0.1,learning_rate =0.001, steps =500):
    # khởi tạo 2 ma trận W, H ngẫu nhiên
    W = np.random.rand(user, K)
    H = np.random.rand(K, item)
    step =0
    while(step < steps):
        for u in range(0, user):
            for i in range(0, item):
                if A[u][i] >0 :
                    r_bar =0
                    for k in range(K):
                        r_bar += np.dot(W[u][k], H[k][i])
                    eui = A[u][i] - r_bar
#                     print(eui)
#                     eui = A[u][i] - np.dot(W[u,:], H[:,i])
#                     print('eui', eui)
                    for k in range(K):
                        W[u][k] += 2*eta*(eui* H[k][i] - learning_rate*W[u][k])
                        H[k][i] += 2*eta*(eui* W[u][k] - learning_rate*H[k][i])
        step +=1
    return np.dot(W,H)

A = np.array([[1,4,5,0,3],
              [5,1,0,5,2],
              [4,1,2,5,0],
              [0,3,4,0,4]])
print('A', A)

user = A.shape[0] # số user
item = A.shape[1] # số item
print('So user:', user)
print('So item:', item)


MF_update =MF_update(A, 3, 0.01, 0.001, 1000)
Y =np.array([[round(MF_update[i][j]) for j in range(item)]for i in range(user)]) #làm tròn
print('Ma tran ban dau:\n ', A)
print('Ma tran sau khi ap dung MF:\n ', MF_update)
print('Ma tran làm tròn:\n',Y)

A [[1 4 5 0 3]
 [5 1 0 5 2]
 [4 1 2 5 0]
 [0 3 4 0 4]]
So user: 4
So item: 5
Ma tran ban dau:
  [[1 4 5 0 3]
 [5 1 0 5 2]
 [4 1 2 5 0]
 [0 3 4 0 4]]
Ma tran sau khi ap dung MF:
  [[1.0005408  3.99888429 4.99651481 3.27652451 3.00023444]
 [4.99627815 0.99862931 2.44909073 4.99999164 2.00044253]
 [4.00031288 1.00361296 1.99823502 4.99733548 2.65803743]
 [2.82361121 2.99716992 4.00135777 5.42596593 3.99739633]]
Ma tran làm tròn:
 [[1. 4. 5. 3. 3.]
 [5. 1. 2. 5. 2.]
 [4. 1. 2. 5. 3.]
 [3. 3. 4. 5. 4.]]


# Bias Matrix Factorization

In [33]:
import numpy as np
# np.random.seed(4)

# Bước 1. Tính nguy
def nguy():
    M =[]
    for i in range(0, A.shape[0]):
        for j in range(0, A.shape[1]):
            if A[i,j] !=0:
                M.append(A[i,j])
    print(M)
    nguy = np.mean(M)
    print('nguy:', nguy)
    return nguy
nguy = nguy()

# Bước 2. Tính bu
def bu():
    tu =0 # tong cac( rating- nguy) trên tử
    num =0 
    arr = []
    for i in range(0, A.shape[0]):
        for j in range(0, A.shape[1]):
            if(A[i,j]!=0):
                tu += (A[i,j] - nguy)
                num +=1
        arr.append( tu/num)
    return arr
bu = bu()
print('bu', bu)

#Bước 3. Tính bi
def bi():
    tu =0 # tong cac( rating- nguy) trên tử
    num =0 
    arr = []
    B = A.T
    for i in range(0, B.shape[0]):
        for j in range(0, B.shape[1]):
            if(B[i,j]!=0):
                tu += (B[i,j] - nguy)
                num +=1
        arr.append( tu/num)
    return arr
bi = bi()
print('bi', bi)
def MF_bias(A, K, nguy, bu, bi, eta=0.1,learning_rate =0.001, steps =500):
    # khởi tạo 2 ma trận W, H ngẫu nhiên
    W = np.random.rand(user, K)
    H = np.random.rand(K, item)
    step =0
    while(step < steps):
        for u in range(0, user):
            for i in range(0, item):
                if A[u][i] >0 :
                    r_bar =0
                    for k in range(K):
                        r_bar += np.dot(W[u][k], H[k][i])
                    pui_bar = nguy + bu[u]+ bi[i] + r_bar
                    eui = A[u][i] - pui_bar
                    
                    #Update weigth: nguy, bu, bi
                    nguy  += eta* eui
                    bu[u] += eta* (eui - learning_rate * bu[u])
                    bi[i] += eta* (eui - learning_rate * bi[i])
                    for k in range(K):
                        W[u][k] += 2*eta*(2*eui* H[k][i] - learning_rate*W[u][k])
                        H[k][i] += 2*eta*(2*eui* W[u][k] - learning_rate*H[k][i])
        step +=1
    return np.dot(W,H)

A = np.array([[1,4,5,0,3],
              [5,1,0,5,2],
              [4,1,2,5,0],
              [0,3,4,0,4]])
print('A', A)

user = A.shape[0] # số user
item = A.shape[1] # số item
print('So user:', user)
print('So item:', item)


MF_bias =MF_bias(A, 3, nguy, bu, bi, 0.01, 0.01, 1000)
MF_predict = MF_bias + nguy
Y =np.array([[round(MF_predict[i][j]) for j in range(item)]for i in range(user)]) #làm tròn
print('Ma tran ban dau:\n ', A)
print('Ma tran sau khi ap dung MF đã chuẩn hóa \n ', MF_bias)
print('Ma trận dự đoán, sau khi cộng thêm nguy:\n', MF_predict)
print('Ma tran làm tròn :\n', Y)

[1, 4, 5, 3, 5, 1, 5, 2, 4, 1, 2, 5, 3, 4, 4]
nguy: 3.2666666666666666
bu [-0.016666666666666607, -0.016666666666666607, -0.09999999999999994, 5.921189464667501e-17]
bi [0.06666666666666672, -0.5523809523809523, -0.2666666666666666, 0.06666666666666672, 5.921189464667501e-17]
A [[1 4 5 0 3]
 [5 1 0 5 2]
 [4 1 2 5 0]
 [0 3 4 0 4]]
So user: 4
So item: 5
Ma tran ban dau:
  [[1 4 5 0 3]
 [5 1 0 5 2]
 [4 1 2 5 0]
 [0 3 4 0 4]]
Ma tran sau khi ap dung MF đã chuẩn hóa 
  [[-2.13550073  1.49997821  2.04868136  0.42539996  0.14596342]
 [ 1.92547203 -1.40946515 -1.14174208  1.53010736 -0.77207332]
 [ 1.36084533 -0.98310591 -0.4348894   1.94500141 -0.43340585]
 [-0.2419217   0.25579084  0.80145627  1.14714536  0.87621316]]
Ma trận dự đoán, sau khi cộng thêm nguy:
 [[1.13116593 4.76664487 5.31534802 3.69206662 3.41263009]
 [5.1921387  1.85720152 2.12492459 4.79677402 2.49459335]
 [4.627512   2.28356076 2.83177727 5.21166808 2.83326082]
 [3.02474496 3.52245751 4.06812294 4.41381203 4.14287983]]
Ma 