In [150]:
import numpy as np
np.random.seed(4)
def MF(A, K, eta=0.1, steps =500):
    # khởi tạo 2 ma trận W, H ngẫu nhiên
    W = np.random.rand(user, K)
    H = np.random.rand(K, item)
    step =0
    while(step < steps):
        for u in range(0, user):
            for i in range(0, item):
                if A[u][i] >0 :
                    r_bar =0
                    for k in range(K):
                        r_bar += np.dot(W[u][k], H[k][i])
                    eui = A[u][i] - r_bar
#                     print(eui)
#                     eui = A[u][i] - np.dot(W[u,:], H[:,i])
#                     print('eui', eui)
                    for k in range(K):
                        W[u][k] += 2*eta*(eui* H[k][i])
                        H[k][i] += 2*eta*(eui* W[u][k])
        step +=1
    return np.dot(W,H)

A = np.array([[1,4,5,0,3],
              [5,1,0,5,2],
              [4,1,2,5,0],
              [0,3,4,0,4]])
print('A', A)

user = A.shape[0] # số user
item = A.shape[1] # số item
print('So user:', user)
print('So item:', item)


MF =MF(A,3,0.01,1000)
Y =np.array([[round(MF[i][j]) for j in range(item)]for i in range(user)]) #làm tròn
print('Ma tran ban dau:\n ', A)
print('Ma tran sau khi ap dung MF:\n ', MF)
print('Ma tran làm tròn:\n',Y)

A [[1 4 5 0 3]
 [5 1 0 5 2]
 [4 1 2 5 0]
 [0 3 4 0 4]]
So user: 4
So item: 5
Ma tran ban dau:
  [[1 4 5 0 3]
 [5 1 0 5 2]
 [4 1 2 5 0]
 [0 3 4 0 4]]
Ma tran sau khi ap dung MF:
  [[0.99998889 3.99990112 5.00004926 4.2786538  3.00002301]
 [4.99989558 0.99981686 2.0420051  5.00009706 2.00005792]
 [4.00010166 1.00012312 1.99999965 4.99990287 0.77849969]
 [3.1224655  3.00012682 3.99995716 4.20169752 3.99995   ]]
Ma tran làm tròn:
 [[1. 4. 5. 4. 3.]
 [5. 1. 2. 5. 2.]
 [4. 1. 2. 5. 1.]
 [3. 3. 4. 4. 4.]]
